--INSERT INTO t_enable VALUES(1,'AAA');
--INSERT INTO t_enable VALUES(2,'BBB');

--INSERT INTO t_enable VALUES(3,NULL);

--ALTER TABLE t_enable
--DISABLE CONSTRAINT te_name_nn;

--INSERT INTO t_enable VALUES(3,NULL);

--ALTER TABLE t_enable
--ENABLE NOVALIDATE CONSTRAINT te_name_nn;

--SELECT * FROM t_enable;

INSERT INTO t_enable VALUES(4,NULL);