--제약 조건 활성화
--INSERT INTO T_NOVALIDATE VALUES(1,'DDD');

--ORA-00001: 무결성 제약 조건(SCOTT.SYS_C007323)에 위배됩니다

--제약 조건 비활성화
--ALTER TABLE T_NOVALIDATE 
--DISABLE NOVALIDATE CONSTRAINT SYS_C007323;

--INSERT INTO T_NOVALIDATE VALUES(1,'DDD');

SELECT * FROM T_NOVALIDATE;