DROP TABLE BOARD 
	CASCADE CONSTRAINTS;

CREATE TABLE BOARD (
	SEQ NUMBER(8) NOT NULL,
	TITLE NVARCHAR2(50) NOT NULL,
	CONTENTS CLOB,
	DIV VARCHAR2(2),
	READ_CNT NUMBER(8) DEFAULT 0,
	REG_ID VARCHAR2(30 BYTE),
	REG_DT DATE DEFAULT SYSDATE,
	MOD_ID VARCHAR2(30 BYTE),
	MOD_DT DATE DEFAULT SYSDATE
);

COMMENT ON TABLE BOARD IS '게시판';
COMMENT ON COLUMN BOARD.SEQ IS '순번';
COMMENT ON COLUMN BOARD.TITLE IS '제목';
COMMENT ON COLUMN BOARD.CONTENTS IS '내용';
COMMENT ON COLUMN BOARD.DIV IS '구분';
COMMENT ON COLUMN BOARD.READ_CNT IS '조회수';
COMMENT ON COLUMN BOARD.REG_ID IS '등록자';
COMMENT ON COLUMN BOARD.REG_DT IS '등록일';
COMMENT ON COLUMN BOARD.MOD_ID IS '수정자';
COMMENT ON COLUMN BOARD.MOD_DT IS '수정일';

CREATE UNIQUE INDEX PK_BOARD
	ON BOARD (
		SEQ ASC
	);

ALTER TABLE BOARD
	ADD
		CONSTRAINT PK_BOARD
		PRIMARY KEY (
			SEQ
		);