CREATE TABLE COM_CODE (
	MASTER_ID VARCHAR2(30 BYTE) NOT NULL,
	DETAIL_ID VARCHAR2(30 BYTE) NOT NULL,
	MASTER_NM NVARCHAR2(50),
	DETAIL_NM NVARCHAR2(50),
	USE_YN CHAR(1) DEFAULT 'Y',
	ORDR NUMBER(4),
	REG_ID VARCHAR2(30 BYTE),
	REG_DT DATE DEFAULT SYSDATE,
	MOD_ID VARCHAR2(30 BYTE),
	MOD_DT DATE DEFAULT SYSDATE
);

COMMENT ON TABLE COM_CODE IS '공통 코드';
0
COMMENT ON COLUMN COM_CODE.MASTER_ID IS '마스터코드ID';

COMMENT ON COLUMN COM_CODE.DETAIL_ID IS '상세코드ID';

COMMENT ON COLUMN COM_CODE.MASTER_NM IS '마스터코드명';

COMMENT ON COLUMN COM_CODE.DETAIL_NM IS '상세코드명';

COMMENT ON COLUMN COM_CODE.USE_YN IS '사용여부';

COMMENT ON COLUMN COM_CODE.ORDR IS '순서';

COMMENT ON COLUMN COM_CODE.REG_ID IS '등록자';

COMMENT ON COLUMN COM_CODE.REG_DT IS '등록일';

COMMENT ON COLUMN COM_CODE.MOD_ID IS '수정자';

COMMENT ON COLUMN COM_CODE.MOD_DT IS '수정일';

CREATE UNIQUE INDEX PK_COM_CODE
	ON COM_CODE (
		MASTER_ID ASC,
		DETAIL_ID ASC
	);

ALTER TABLE COM_CODE
	ADD
		CONSTRAINT PK_COM_CODE
		PRIMARY KEY (
			MASTER_ID,
			DETAIL_ID
		);