--CREATE TABLE test_ex999(
--	col1 VARCHAR2(2),
--	col2 VARCHAR2(2),
--	col3 NUMBER(1)
--);
--INSERT INTO test_ex999 VALUES('A',NULL,1);
--INSERT INTO test_ex999 VALUES('B','A',2);
--INSERT INTO test_ex999 VALUES('C','A',3);
--INSERT INTO test_ex999 VALUES('D','B',4);
SELECT MAX(LEVEL)
FROM test_ex999
WHERE COL3 <> 2
START WITH COL3 = 4
CONNECT BY COL1 = PRIOR COL2;