DROP TABLE MEMBER 
	CASCADE CONSTRAINTS;

CREATE TABLE MEMBER (
	USER_ID VARCHAR2(30 BYTE) NOT NULL,
	NAME NVARCHAR2(7) NOT NULL,
	PASSWORD VARCHAR2(30 BYTE),
	REG_DT DATE DEFAULT SYSDATE
);

COMMENT ON TABLE MEMBER IS '회원';

COMMENT ON COLUMN MEMBER.USER_ID IS '사용자ID';

COMMENT ON COLUMN MEMBER.NAME IS '이름';

COMMENT ON COLUMN MEMBER.PASSWORD IS '비밀번호';

COMMENT ON COLUMN MEMBER.REG_DT IS '등록일';

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		USER_ID ASC
	);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			USER_ID
		);