--IDX_DEPT2_DNAME
--모니터링 START
--ALTER INDEX IDX_DEPT2_DNAME MONITORING USAGE;

--SELECT *
--  FROM dept2
-- WHERE dname > 'A';

--모니터링 STOP
--ALTER INDEX IDX_DEPT2_DNAME NOMONITORING USAGE;

--모니터링 확인 : V$OBJECT_USAGE
--SELECT table_name,index_name,used
--  FROM V$OBJECT_USAGE
-- WHERE INDEX_NAME = 'IDX_DEPT2_DNAME';
 

