--BEGIN 
--	FOR i IN 1..700000 LOOP
--		INSERT INTO SCOTT.REORG 
--		VALUES(i,DBMS_RANDOM.STRING('L',19),DBMS_RANDOM.STRING('U',19));
--	
--	END LOOP;
--	COMMIT;
--END;
--/

SELECT COUNT(*) FROM SCOTT.REORG;