DROP INDEX PK_PW_DATE;

DROP TABLE PW_DATE 
	CASCADE CONSTRAINTS;

CREATE TABLE PW_DATE (
	YEAR CHAR(4 BYTE) NOT NULL,
	MONTH NUMBER(2) NOT NULL
);

COMMENT ON TABLE PW_DATE IS 'PW_DATE';

COMMENT ON COLUMN PW_DATE.YEAR IS '³âµµ';

COMMENT ON COLUMN PW_DATE.MONTH IS '¿ù';

CREATE UNIQUE INDEX PK_PW_DATE
	ON PW_DATE (
		YEAR ASC,
		MONTH ASC
	);

ALTER TABLE PW_DATE
	ADD
		CONSTRAINT PK_PW_DATE
		PRIMARY KEY (
			YEAR,
			MONTH
		);