DROP INDEX PK_PW_CALENDAR;

DROP TABLE PW_CALENDAR 
	CASCADE CONSTRAINTS;

CREATE TABLE PW_CALENDAR (
	YEAR NUMBER(4) NOT NULL,
	MONTH NUMBER(2) NOT NULL,
	DAYNO NUMBER(2) NOT NULL,
	WEEKNO NUMBER(1),
	WEEK VARCHAR2(3 BYTE)
);

COMMENT ON TABLE PW_CALENDAR IS '달력';

COMMENT ON COLUMN PW_CALENDAR.YEAR IS '년도';

COMMENT ON COLUMN PW_CALENDAR.MONTH IS '월';

COMMENT ON COLUMN PW_CALENDAR.DAYNO IS '일';

COMMENT ON COLUMN PW_CALENDAR.WEEKNO IS '주차';

COMMENT ON COLUMN PW_CALENDAR.WEEK IS '요일';

CREATE UNIQUE INDEX PK_PW_CALENDAR
	ON PW_CALENDAR (
		YEAR ASC,
		MONTH ASC,
		DAYNO ASC
	);

ALTER TABLE PW_CALENDAR
	ADD
		CONSTRAINT PK_PW_CALENDAR
		PRIMARY KEY (
			YEAR,
			MONTH,
			DAYNO
		);