--CREATE TABLE cat_a(no NUMBER, name VARCHAR2(1));
--INSERT INTO cat_a VALUES (1,'A');
--INSERT INTO cat_a VALUES (2,'B');
--SELECT * FROM cat_a;
--CREATE TABLE cat_b(no NUMBER, name VARCHAR2(1));
--INSERT INTO cat_b VALUES (1,'C');
--INSERT INTO cat_b VALUES (2,'D');
--SELECT * FROM cat_b;
--CREATE TABLE cat_c(no NUMBER, name VARCHAR2(1));
--INSERT INTO cat_c VALUES (1,'E');
--INSERT INTO cat_c VALUES (2,'F');
--SELECT * FROM cat_c;
--SELECT a.name,b.name,c.name
--  FROM cat_a a,cat_b b,cat_c c
-- WHERE a.no = b.no AND 
--	   b.no = c.no AND
--	   c.no = a.no
--;
